codecov: 
 token: 5dbe9f82-3165-417e-9d94-29a0a5e76d75
 require_ci_to_pass: yes
 
ignore:
  - "test"
  - "MVC/controller"
  - "MVC/database"
  - "MVC/view"
  
  status:
    project:
      default:
        target: 80%
