# This workflow will install Python dependencies, run tests and upload code coverage report to CodeCov
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI and Code Coverage

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
    - name: Test with Unit Test
      run: |
        python test/run.py
    - name: Generate Report
      run: |
        coverage run test/run.py
        coverage report
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
        token: 5dbe9f82-3165-417e-9d94-29a0a5e76d75
